### ISSUE TITLE
Getting a generic error when following a directory: other os error adding watcher for path

### ISSUE THREAD

**Issue by berkes** [JoshMcguigan/timetrack#6]
When running `timetrack config`, one directory is fine, but for the other one 
I'm getting `Error other os error adding watcher for path "/home/xxx/Documents"`

Looking at `notify`, it seems this is a generic IO error, but details are lacking.

Is there a way to get the full error somewhere? syslog is not recording anything either.

My system:
```
xxx@xxx:Documents ⌁ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by JoshMcguigan** [comment]
Hi @berkes, thanks for the report. 

Unfortuntately I'm not aware of a way to get more detail out of `notify`. If you have symbolic links in `/home/xxx/Documents` I've seen that cause problems for others in the past, but otherwise I'd probably just try adding subdirectories of the `Documents` folder individually to see if you can narrow down the error.

Sorry I can't be more help here.
